spring:
  h2:
    console:
      enabled: true
  jpa:
    show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        storage_engine: innodb
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    #username: sa
    #password: 1234